### ISSUE TITLE
Builds fine, and runs fine, but `docker-compose up` causes `urllib.error.URLError: <urlopen error [Errno 111] Connection refused>` 

### ISSUE THREAD

**Issue by afxjzs** [gael-thomas/Client-Server-Docker-Compose-example#1]
(Great tutorial btw, please keep up the great work!)

Not sure what the issue is. I get the exact same error from my hand typed version and a cloned app. Everything builds fine, and even loads the page at `localhost:1234`
 
Is this error expected behavior? Mostly more curious than anything and didn't want to clog up the Medium comments with a bunch of code. 

Macbook Air / MacOS 10.14.4

## Full Output
```
projects/docker/demo2                                                                               
▶ docker-compose build
Building server
Step 1/3 : FROM python:latest
 ---> 59a8c21b72d4
Step 2/3 : ADD * /server/
 ---> fca6f8c9bbfa
Step 3/3 : WORKDIR /server/
 ---> Running in 588e837e96d0
Removing intermediate container 588e837e96d0
 ---> 14d835e4bef3
Successfully built 14d835e4bef3
Successfully tagged demo2_server:latest
Building client
Step 1/3 : FROM python:latest
 ---> 59a8c21b72d4
Step 2/3 : ADD client.py /client/
 ---> Using cache
 ---> 88adfeb22bee
Step 3/3 : WORKDIR /client/
 ---> Using cache
 ---> 94e52833afc4
Successfully built 94e52833afc4
Successfully tagged demo2_client:latest

projects/docker/demo2                                                                               
▶ docker-compose up   
Recreating demo2_server_1 ... done
Recreating demo2_client_1 ... done
Attaching to demo2_server_1, demo2_client_1
client_1  | Traceback (most recent call last):
client_1  |   File "/usr/local/lib/python3.7/urllib/request.py", line 1317, in do_open
client_1  |     encode_chunked=req.has_header('Transfer-encoding'))
client_1  |   File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
client_1  |     self._send_request(method, url, body, headers, encode_chunked)
client_1  |   File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
client_1  |     self.endheaders(body, encode_chunked=encode_chunked)
client_1  |   File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
client_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
client_1  |   File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
client_1  |     self.send(msg)
client_1  |   File "/usr/local/lib/python3.7/http/client.py", line 956, in send
client_1  |     self.connect()
client_1  |   File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
client_1  |     (self.host,self.port), self.timeout, self.source_address)
client_1  |   File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
client_1  |     raise err
client_1  |   File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
client_1  |     sock.connect(sa)
client_1  | ConnectionRefusedError: [Errno 111] Connection refused
client_1  | 
client_1  | During handling of the above exception, another exception occurred:
client_1  | 
client_1  | Traceback (most recent call last):
client_1  |   File "./client.py", line 12, in <module>
client_1  |     fp = urllib.request.urlopen("http://localhost:3009/")
client_1  |   File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
client_1  |     return opener.open(url, data, timeout)
client_1  |   File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
client_1  |     response = self._open(req, data)
client_1  |   File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
client_1  |     '_open', req)
client_1  |   File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
client_1  |     result = func(*args)
client_1  |   File "/usr/local/lib/python3.7/urllib/request.py", line 1345, in http_open
client_1  |     return self.do_open(http.client.HTTPConnection, req)
client_1  |   File "/usr/local/lib/python3.7/urllib/request.py", line 1319, in do_open
client_1  |     raise URLError(err)
client_1  | urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
demo2_client_1 exited with code 1
```

**Comment by gaelgthomas** [comment]
Hello @afxjzs,

Thank you for your feedback!

Your problem seems to come from the client. The client can't connect to host port.
It's curious because in **docker-compose.yml** at line 53, we put: `network_mode: host` command to share the host with the container.

I noticed that you modified your code.

```
client_1  | Traceback (most recent call last):
client_1  |   File "./client.py", line 12, in <module>
client_1  |     fp = urllib.request.urlopen("http://localhost:3009/")
```

If you access your website with **localhost:1234**, your **client.py** must listen the same port. Please change `http://localhost:3009/` to `http://localhost:1234/`.

Hope my answer solve your problem.
I keep the issue open in waiting of your response!

**Comment by afxjzs** [comment]
I had changed both ports to see if there was something randomly running on port `1234` ... sorry for the confusing change. I got the exact same error when I ran a straight up clone of this repo, so that had me thinking it was something on my machine, so i tried a different port. 

What's odd is that the 2 services do actually work. When i `docker-compose run`, i see that error, but i am able to load the website at `localhost:1234` (although exactly once. a reload fails, but i think that's the correct operation based on a comment on blog post)

**Comment by gaelgthomas** [comment]
It seems that your server is transmitting correctly, but the client cannot connect to the local port. The docker-composer must not correctly share the network with the command: "network_mode: host". What is your version of docker-composer and docker?

**Comment by shaojunda** [comment]
try to restart docker

**Comment by gaelgthomas** [comment]
Hello,

I am closing the subject because it has no more answers since May 2019.

Feel free to reopen an issue if you have a question!
